language: objective-c
osx_image: xcode7.1
env:
  - SCHEME=Vinyl
script:
  - xctool -project Vinyl.xcodeproj -scheme $SCHEME test sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
notifications:
  slack: ios:0sE9PZaoizGktMBoE1LB9uWo