language: objective-c
osx_image: xcode7.2
install:
  - git submodule update --init --recursive
script:
  - set -o pipefail
  - xcodebuild test -project Vinyl.xcodeproj -scheme Vinyl-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s' -enableCodeCoverage YES | xcpretty
  - xcodebuild test -project Vinyl.xcodeproj -scheme Vinyl-Mac | xcpretty
  - xcodebuild test -project Vinyl.xcodeproj -scheme Vinyl-tvOS -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 1080p" | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack: ios:0sE9PZaoizGktMBoE1LB9uWo
